parameters:
    alsatian_form.parameters.extensible.enabled_Types: []
    
services:
    alsatian_form.form_type.abstract_routable:
        class: Alsatian\FormBundle\Form\AbstractRoutableType
        abstract:  true
        public: false
        calls:
            - [setRouter,["@router"]]

# Extensible types

    alsatian_form.form_extension.extensible:
        class: Alsatian\FormBundle\Form\Extensions\ExtensibleExtension
        public: false
        arguments: ["@alsatian_form.form_event_subscriber.extensible"]
             
    alsatian_form.form_event_subscriber.extensible:
        class: Alsatian\FormBundle\Form\Extensions\ExtensibleSubscriber
        public: false
        arguments: [%alsatian_form.parameters.extensible.enabled_Types%]
        calls:
            - [setEntityManager,["@doctrine.orm.entity_manager"]]
            - [setDocumentManager,["@doctrine.odm.mongodb.document_manager"]]

    alsatian_form.form_type.abstract_extensible:
        class: Alsatian\FormBundle\Form\AbstractRoutableType
        parent: alsatian_form.form_type.abstract_routable
        abstract:  true
        public: false

    alsatian_form.form_type.extensible_choice:
        class: Alsatian\FormBundle\Form\ExtensibleChoiceType
        parent: alsatian_form.form_type.abstract_extensible
        public: false
        arguments: [%alsatian_form.parameters.extensible_choice.attr_class%]

    alsatian_form.form_type.extensible_entity:
        class: Alsatian\FormBundle\Form\ExtensibleEntityType
        parent: alsatian_form.form_type.abstract_extensible
        public: false
        arguments: [%alsatian_form.parameters.extensible_entity.attr_class%]

    alsatian_form.form_type.extensible_document:
        class: Alsatian\FormBundle\Form\ExtensibleDocumentType
        parent: alsatian_form.form_type.abstract_extensible
        public: false
        arguments: [%alsatian_form.parameters.extensible_document.attr_class%]

# Others Types
    alsatian_form.form_type.autocomplete:
        class: Alsatian\FormBundle\Form\AutocompleteType
        parent: alsatian_form.form_type.abstract_routable
        arguments: [%alsatian_form.parameters.autocomplete.attr_class%]

    alsatian_form.form_type.datepicker:
        class: Alsatian\FormBundle\Form\DatePickerType
        arguments: ["@request_stack"]

    alsatian_form.form_type.datetimepicker:
        class: Alsatian\FormBundle\Form\DateTimePickerType
        arguments: ["@request_stack"]
