parameters:
    alsatian_form.parameters.select2_choice.attr_class: select2
    alsatian_form.parameters.select2_entity.attr_class: select2
    alsatian_form.parameters.select2_document.attr_class: select2

    alsatian_form.parameters.select2_entity.choice_label: ajaxName
    alsatian_form.parameters.select2_document.choice_label: ajaxName

    alsatian_form.parameters.select2.enabled_Types: []
    
services:
# Select 2
    alsatian_form.form_extension.select2:
        class: Alsatian\FormBundle\Form\Extensions\AjaxExtension
        public: false
        arguments: ["@alsatian_form.form_event_subscriber.select2"]
             
    alsatian_form.form_event_subscriber.select2:
        class: Alsatian\FormBundle\Form\Extensions\AjaxSubscriber
        public: false
        arguments: [%alsatian_form.parameters.select2.enabled_Types%]
        calls:
            - [setEntityManager,["@doctrine.orm.entity_manager"]]
            - [setDocumentManager,["@doctrine.odm.mongodb.document_manager"]]

    alsatian_form.form_type.select2_choice:
        class: Alsatian\FormBundle\Form\Select2ChoiceType
        public: false
        arguments:[%alsatian_form.parameters.select2_choice.attr_class%]
        calls:
            - [setRouter,["@router"]]

    alsatian_form.form_type.select2_entity:
        class: Alsatian\FormBundle\Form\Select2EntityType
        public: false
        arguments:[%alsatian_form.parameters.select2_entity.attr_class%,%alsatian_form.parameters.select2_entity.choice_label%]
        calls:
            - [setRouter,["@router"]]

    alsatian_form.form_type.select2_document:
        class: Alsatian\FormBundle\Form\Select2DocumentType
        public: false
        arguments:[%alsatian_form.parameters.select2_document.attr_class%,%alsatian_form.parameters.select2_document.choice_label%]
        calls:
            - [setRouter,["@router"]]

# Others ...
    alsatian_form.form_type.autocomplete:
        class: Alsatian\FormBundle\Form\AutocompleteType
        tags:
             - { name: form.type }
        arguments: ["@router"]

    alsatian_form.form_type.datepicker:
        class: Alsatian\FormBundle\Form\DatePickerType
        tags:
            - { name: form.type, alias: datepicker }
        arguments: ["@request_stack"]

    alsatian_form.form_type.datetimepicker:
        class: Alsatian\FormBundle\Form\DateTimePickerType
        tags:
            - { name: form.type, alias: datetimepicker }
        arguments: ["@request_stack"]
